version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
    build-and-test:
        docker:
            - image: circleci/node:10.21.0
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "./functions/package.json" }}
                    - v1-dependencies-
            - run: 
                working_directory: ~/project/functions
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "./functions/package.json" }}
                paths:
                    - ./project/functions/node_modules
            - run: 
                working_directory: ~/project/functions
                command: npm test
            #comienza la parte de la app en react
            - restore_cache:
                keys:
                    - v1-react-dependencies-{{ checksum "./package.json" }}
                    - v1-react-dependencies-
            - run: 
                name: Installing React dependencies
                command: npm install
            - save_cache:
                name: Caching React dependencies
                key: v1-react-dependencies-{{ checksum "./package.json" }}
                paths:
                    - ./project/node_modules
            - run:
                name: Build React App
                command: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                    - ./
            - slack/notify:
                channel: C014S6X3X9U
                color: '#42e2f4'
                message: Trabajo BUILD-AND-TEST finalizado

    deploy-job:
        docker:
            - image: circleci/node:10.21.0
        steps:
            - attach_workspace:
                at: ~/project
            - run:
                name: Deploy Hosting and Functions to Firebase
                command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
            - slack/notify:
                channel: C014S6X3X9U
                color: '#3358FF'
                message: Trabajo DEPLOY finalizado   
        
    hold-notify:
        docker:
            - image: circleci/node:10.21.0
        steps:
            - slack/approval:
                channel: C014S6X3X9U
                color: '#FFF633'
                message: Trabajo en HOLD, se necesita APROBACIÓN para continuar
            - hold:
                type: approval
                

workflows:
    ci-cd-workflow:
        jobs:
            - build-and-test
            - hold-notify:
                requires:
                    - build-and-test
                filters:
                    branches:
                        only: master
            - deploy-job:
                requires:
                    - hold
                filters:
                    branches:
                        only: master
                